# Generated by Django 6.0.2 on 2026-02-27 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nome completo')),
                ('can_view_dashboard', models.BooleanField(default=True, verbose_name='Ver Dashboard')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Ver Relatórios')),
                ('can_view_settings', models.BooleanField(default=False, verbose_name='Ver Configurações')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='Gerenciar Usuários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
