# Generated by Django 6.0.2 on 2026-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Chave')),
                ('value', models.TextField(blank=True, default='', verbose_name='Valor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do Sistema',
                'verbose_name_plural': 'Configuracoes do Sistema',
            },
        ),
    ]
