# Generated by Django 6.0.2 on 2026-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='event',
            field=models.CharField(choices=[('login_ok', 'Login bem-sucedido'), ('login_fail', 'Tentativa de login falha'), ('logout', 'Logout'), ('lockout', 'IP bloqueado')], max_length=20),
        ),
    ]
